namespace PuzzleIdentification
{
    static class Data
    {
        public static readonly string[][] PuzzleNames =
        {
            new string[]
            {
                "Where's the Village?",
                "The Crank and Slot",
                "Strange Hats",
                "Where's My House?",
                "Clock Hands",
                "Light Weight",
                "Wolves and Chicks",
                "Farm Work",
                "One Poor Pooch",
                "Four Digits",
                "Arc and Line",
                "Make a Rectangle",
                "Sinking Ship",
                "Which Chair?",
                "How Many Are Left?",
                "Triangles and Ink",
                "Five-Card Shuffle",
                "Of Dust and Dustpan",
                "Car Park Gridlock",
                "Unfriendly Commute",
                "Pill Prescription",
                "Pigpen Partitions",
                "Juice Pitchers",
                "Milk Pitchers",
                "Equilateral Triangle",
                "Bottle Full of Germs",
                "Bickering Brothers",
                "Find the Dot",
                "Five Suspects",
                "One-Line Puzzle 1",
                "Racetrack Riddle",
                "Sweet Jars",
                "Light Which One?",
                "How Many Sheets?",
                "Strange Dots",
                "Too Many Mice",
                "Brother and Sister",
                "Island Hopping",
                "One-Line Puzzle 2",
                "Father's Age",
                "Spare Change",
                "The Camera and Case",
                "Three Umbrellas",
                "Stamp Stumper",
                "Lunar Weight",
                "Star in the Sky",
                "On the Run",
                "Cats and Mice",
                "1,000 Times",
                "Number Maze",
                "The Town Barbers",
                "Find a Star",
                "Fish Thief",
                "Monster!",
                "The Odd Sandwich",
                "The Lazy Guard",
                "Cut Which One?",
                "Get the Ball Out! 1",
                "The Longest Path",
                "Weighing Cats",
                "Pin Board Shapes",
                "A Tricky Inheritance",
                "Mother's Age",
                "Odd Equations",
                "Letters and Numbers",
                "Five Borrowers",
                "How Many Sweets?",
                "Find the Pentagons",
                "Chocolate Puzzle",
                "The Shattered Vase",
                "Sausage Thief",
                "Truth and Lies",
                "How Many Squares?",
                "A Broken Window",
                "The Wire Cube",
                "Flower Garden",
                "Which Job?",
                "Water Pitchers",
                "Apples to Oranges",
                "Too Many Queens 1",
                "Too Many Queens 2",
                "Too Many Queens 3",
                "Too Many Queens 4",
                "Which Boxes to Move?",
                "Train Speed",
                "Squares and Circles",
                "Ferris Wheel Riddle",
                "Leaky Tank",
                "Which Way?",
                "Get the Ball Out! 2",
                "Pattern Matching",
                "Wash Up",
                "Over the River",
                "Get the Ball Out! 4",
                "A Magic Square",
                "On the Stairs",
                "Maiden's Escape",
                "Card Order",
                "33333!",
                "Seven Squares",
                "Splitting It Up",
                "Aces and the Joker",
                "Wood Cutouts",
                "A Sweet Treat",
                "Rolling a Three",
                "How Many Glasses?",
                "Worm in the Apple",
                "Not Knots?",
                "Laziest Man on Earth",
                "The Vanishing Cube",
                "Making a Square",
                "My Beloved",
                "Pet Menagerie",
                "Tetrahedron Trial",
                "Odd Box Out",
                "The Largest Total",
                "Painting a Cube",
                "Red and Black Cards",
                "Red and Blue 1",
                "Get the Ball Out! 3",
                "Diamond in the Flag",
                "The Next Die",
                "Tons of Triangles",
                "The Rope Ladder",
                "Rolling the Die",
                "Red and Blue 2",
                "Perimeter Perplexer",
                "Number Lock",
                "Four Balls",
                "Too Many Queens 5",
                "Heavier or Lighter?",
                "Princess's Escape",
                "Finish the Equation",
                "Land Disputes",
                "Queen's Escape"
            },
            new string[]
            {
                "Dr Schrader's Map",
                "The Doctor's Home",
                "Which Key?",
                "A Secure Room",
                "Luke's Trunk",
                "Piles of Pancakes 1",
                "Four Couples",
                "Luke's Big Dinner",
                "Stacked Glasses",
                "A Work of Art",
                "Trees in the Forest",
                "Clouds and Sky",
                "On Your Plate",
                "Red Caps",
                "Tom's True Identity",
                "Crazy Daisies",
                "The Ant's Journey",
                "The Shoe Maze",
                "The Train Journey",
                "The Shoe Shop Thief",
                "Pass It On!",
                "Cleaning Up 1",
                "A Sour Defeat",
                "A Strip of Paper",
                "Surviving in the Wild",
                "Train Swap",
                "A Dramatic Farewell",
                "The Warped Wheel",
                "Which Arrow?",
                "The Wrong Date",
                "Pass the Apples",
                "It's a Wrap",
                "Fishing Net",
                "Trees on an Old Road",
                "Which House Where?",
                "The Trapped Bird",
                "World's Best Golfer",
                "Four Horses",
                "A Change of Clothes",
                "The Patterned Box",
                "Cube Halves",
                "Board Cutter 1",
                "Board Cutter 2",
                "Tangled Ropes",
                "Baggage Claim",
                "Odd Shape Out",
                "The Mayoral Election",
                "Who's Mr Anderson?",
                "A Royal Show-off",
                "Misinformootion",
                "Crazy Cats",
                "Hat Weather",
                "Boys' Club",
                "Painting the Flag",
                "Sammy's Necklace",
                "The Door's Code",
                "Smell the Roses",
                "In the Tunnel",
                "A Ticket to Where?",
                "Plaza Puzzle",
                "Where's the Hotel?",
                "Smell the Roses Again",
                "Numbered Cards",
                "Stones in a Vase",
                "The Ancient Map",
                "The Locked Box",
                "Sammy's Working Week",
                "Hat Etiquette",
                "Copying the Menu",
                "Jewelled Necklaces",
                "How Old is She?",
                "Scrambled Photos",
                "Can Conundrum",
                "Sealing Off the Smell",
                "Sweets for Five",
                "Top of the Tower",
                "Balancing Ornaments",
                "A Maze of Doors",
                "The Gear Switch",
                "The Puzzling Lift",
                "The Old Safe",
                "Restarting the Lift",
                "Piles of Pancakes 2",
                "Piles of Pancakes 3",
                "The Missing Shape",
                "Perplexing Figures",
                "Different Suits",
                "The Frog's Path",
                "Flower Bed Fun",
                "The Unusual Fountain",
                "Sharing the Wealth",
                "Precious Metals",
                "How Old Am I?",
                "Puzzling Cubes",
                "Box of Books",
                "A Ghostly Puzzle",
                "A Starry Sky",
                "Jars and Cans 1",
                "Jars and Cans 2",
                "A Rickety Bridge",
                "Disappearing Act 1",
                "Disappearing Act 2",
                "Disappearing Act 3",
                "Disappearing Act 4",
                "Disappearing Act 5",
                "The Knight's Tour 1",
                "The Knight's Tour 2",
                "The Knight's Tour 3",
                "Walking the Dog",
                "Chelmey's Route",
                "How Many Turns?",
                "Turn on the Light",
                "A Stack of Dice",
                "Fair Compensation",
                "Tricky Digits",
                "The Torn Photo",
                "Three Couples",
                "Cleaning Up 2",
                "The Fake Coins",
                "Tug of War",
                "Light the Way 1",
                "Light the Way 2",
                "Light the Way 3",
                "UFOs Spotted!",
                "Forest Mushrooms",
                "Slippery Crossings 1",
                "Slippery Crossings 2",
                "Slippery Crossings 3",
                "The Messy Mole",
                "The Strange Painting",
                "How to Escape?",
                "Sharing Paintings",
                "Grab the Key",
                "Steam Power",
                "The Magic Lock",
                "The Hidden Door",
                "One True Sword",
                "The Elysian Box",
                "Coast to Coast",
                "One Extra Block",
                "Disappearing Act 6",
                "The Scholar's Life",
                "Letter Calculations",
                "Super Pancakes",
                "500 Pearls",
                "Angles in a Box",
                "Sliding Labyrinth",
                "Eight Cards",
                "Number Cycle",
                "The Knight's Tour 4",
                "John's Score",
                "The Card Tournament",
                "Ultimate Escape"
            },
            new string[]
            {
                "A Party Crasher",
                "The Clock Shop",
                "Bus Scheduling",
                "Moving Day",
                "The Timepiece",
                "Eye on the Needles",
                "What's the Time?",
                "The Odd Clock",
                "Cogged Down",
                "Day Dreaming",
                "The Professor's Hat",
                "Follow the Arrows",
                "Pick the Pen",
                "Find the Station!",
                "How Many Boxes?",
                "Day Dreaming 2",
                "The Scrawled Note",
                "Slippery Trip",
                "Chequerboard Bridge",
                "Making the Rounds",
                "Medicine Time",
                "X-ray Vision",
                "The Hidden Number",
                "No-Go Arrows",
                "How Long?",
                "Upon Reflection",
                "A Game of Cards",
                "Slot Machine Gun!",
                "Four Rooms",
                "Biscuit Baffler",
                "Pair-Shaped",
                "Broken Lance",
                "Brothers 'n' Sisters",
                "The Mysterious Memo",
                "Twisted Tunnels",
                "Henchman Hunt",
                "Cat Romance",
                "Cluttered Case",
                "Where's My Coat?",
                "Missing Tiles",
                "Thirsty Work",
                "Shape of the Key",
                "Making the Cut",
                "Clock the Tower",
                "How Many People?",
                "A Heartfelt Heart",
                "The Shady Trio",
                "1/1000",
                "The Missing Block",
                "Where Is This?",
                "Park the Car",
                "The Chessboard",
                "Making Another Cut",
                "Lunchtime!",
                "Six Whiny Spectators",
                "Five Stamps",
                "Mispainted Plates",
                "Gravity Maze",
                "Leapfrogs",
                "The Inheritance",
                "A Tunnel Out",
                "Lunar Leapfrogs",
                "Which Finger?",
                "Break Time",
                "Funny Shapes",
                "Flower Vases",
                "Pork Noodle Line-Up",
                "Paper Cuts",
                "Pearl Diving",
                "The Third Youngest",
                "Wall Paint Problem",
                "Tricolour Template",
                "Tricky Tilework",
                "Slippery Trip 2",
                "The Chick's Shadow",
                "Around the Table",
                "Timely Arrivals",
                "Bunny Hop",
                "Five Swimmers",
                "Making a Scene",
                "Diced Dates",
                "Flour Power",
                "A Tidy Bookshelf",
                "Four Cross the River",
                "Noodlin' Around",
                "The Impassable Gate",
                "Pocket Money Poser",
                "The Discount",
                "Photo Finish",
                "Eye of the Dragon",
                "Strange Glasses",
                "Stolen Goods",
                "The Mirror Maze",
                "The Dragon Walkway",
                "Looking Up",
                "First Step?",
                "A Blind Escape",
                "Slippery Trip 3",
                "An Odd Invitation",
                "The Lost Number",
                "Shy Lads and Lasses",
                "Balance your Books",
                "Fill the Pool",
                "The Cake Gobbler",
                "The Fingerprint",
                "Four Stamps",
                "The Henclucky Derby",
                "Dog, Dog, Cat!",
                "Three Blocks",
                "A Zero-Sum Game",
                "Puzzling Legend",
                "Ladder Puzzle",
                "One Step at a Time",
                "Rope Puzzle",
                "Plus Key",
                "Which Direction?",
                "The Secret Letter",
                "Scrutinised Screws",
                "Swap to Unlock",
                "A Cryptic Combo",
                "Arrow Flow",
                "Key Code Puzzle",
                "Cat's-Eye View",
                "The Final Tile",
                "Connect the Bots",
                "Ten-Step Solution",
                "A Real Heart Swapper",
                "Reverse Rotation",
                "Block Blockade",
                "The Final Puzzle",
                "The Price of the Pen",
                "Calendar Collage",
                "The Two Necklaces",
                "A Question of Taste",
                "Jam Weight",
                "Destination Station",
                "Choc-hole-ate",
                "Quirky Clockwork",
                "Bricks 'n' Bullion",
                "Ripple Effect",
                "A Roll of the Die",
                "The Marked Cup",
                "Boards into Numbers",
                "Mr 8:20",
                "Time Cards",
                "Birds on a Wire",
                "Paving the Way",
                "Mathematchsticks",
                "Strange Symbols",
                "Sisterly Sums",
                "A Difference of 39",
                "Tinned Trouble",
                "An Extra Block",
                "A Stacked Deck",
                "Block Parity",
                "ABCs...and Ds",
                "The Curious Keyholes",
                "From A to D",
                "Impassable Gate 2",
                "Plot Patchwork",
                "Black Hat, White Hat",
                "Tinned Trouble 2",
                "Time Times Three",
                "Calendar Conundrum",
                "One Big Necklace",
                "Perplexing Produce",
                "Impassable Gate 3",
                "The Time Machine"
            },
            new string[]
            {
                "A Secret Message",
                "Tourist Spotting",
                "Pick a Package",
                "Reloading the Cart",
                "River Crossing",
                "Letter Box Plate",
                "Mopping Up",
                "Hall of Mirrors",
                "Curtain Call",
                "Rodent Rations",
                "Assign the Incline",
                "Hotel Rooms",
                "Bucket Race",
                "Cafeteria Cruncher",
                "Eating Point",
                "Captains' Chat",
                "The Same Doll?",
                "Faulty Streetlights",
                "Fish Feud",
                "Kitty Cat Count",
                "Foggy Numbers",
                "Paper Pieces Pair",
                "The Cracked Clock",
                "Moonlight Melancholy",
                "Bun Gourmet",
                "UFO SOS",
                "Rainbow Cottages",
                "Black and White Cats",
                "How Old?",
                "Book Stacks",
                "Light Height",
                "A Kingly Cleanup",
                "Fruit Friends",
                "Baskets of Apples",
                "Sweetie Shapes",
                "How Many Ones?",
                "Seven Coins",
                "Double-Sided Maze",
                "Raven Medals",
                "The Full Reservoir",
                "To See the Stars",
                "Angle Anguish",
                "Armour Antics",
                "Family Portraits",
                "Sign Switching",
                "Overgrown Garden",
                "The Coded Door",
                "Crawling the Web",
                "The Picture's Key",
                "The 26th Card",
                "Family Tides",
                "What Am I?",
                "Tricky Tomes",
                "It's in the Bag",
                "Hat Trick",
                "Fortune Flowers",
                "Route Map Madness",
                "Favourite Umbrella",
                "Lost in the Museum",
                "Dinosaur Bones",
                "Find the File",
                "A Familiar Face",
                "Son's Blunder",
                "Cutting the Cake",
                "Rubble Trouble",
                "Sorting Artefacts",
                "Reflections",
                "The Cat in the Maze",
                "Lanky Lamp Post",
                "Good Neighbours",
                "Fountain Fight",
                "Cap Swap",
                "Bottle Game",
                "Emergency Lighting",
                "Coats of Paint",
                "Swap Over!",
                "How the Bells Toll",
                "Lucky Tablecloth",
                "Sweet Sums",
                "Paint the Plinth",
                "Stick to the Plank",
                "Blockwork Ostrich",
                "Silver Spinner",
                "Fill the Flower Bed",
                "The Bus Stop",
                "Board the Window!",
                "Double-Sided Maze 2",
                "Fuel for the Fire",
                "Wine Wise",
                "Puppet Master",
                "Evacuate!",
                "Key Quandry",
                "Escape Route",
                "Policing the Streets",
                "House Hunting",
                "Seven Towers",
                "How Many Friends?",
                "A Secret Code",
                "A Watched Pot",
                "Cat Catching",
                "Square Goldfish",
                "Window Pain",
                "Cog Confusion",
                "Bridgathon",
                "Bouquet Give Away",
                "Apples Away!",
                "A View of the Rooms",
                "Pendant Pursuit",
                "An Orderly Bookcase",
                "16 Silver Marbles",
                "Couple the Chairs",
                "Repair the Wall",
                "Crystal Carafes",
                "Typing Numbers",
                "Market Shortcut",
                "Stained Glass",
                "A Token Puzzle",
                "Starry Sky Sketch",
                "Window Design",
                "Juice Bottle",
                "Flatfoot Families",
                "Balance the Fruits",
                "The Same Chain",
                "Snake Mummies",
                "The Spectre's Path",
                "Mirror, Mirror",
                "Redial",
                "Watermelon Wonder",
                "The Factory Door",
                "The Four Weights",
                "Dark Maze",
                "Painting Device",
                "Freight Crane",
                "Engine Parts",
                "Hanging Platform",
                "The Same Again",
                "How Many Brothers?",
                "Wire Cutter",
                "Emergency Stop",
                "The Next Attack!",
                "The Red Connection",
                "Switchboard Cipher",
                "Layton's Catapult",
                "Lake Bottom Crest",
                "Cubic Planet Map",
                "Seventy Books",
                "Three-Coloured Cube",
                "Gems in a Box",
                "Marble Swirl Circle",
                "Lily Pad Leapfrog",
                "Coax the Kitty!",
                "A Convenient Tool",
                "Artistic Value",
                "The Winding Cable",
                "One Way",
                "Which Direction?",
                "Emergency Stop 2",
                "Just Jewels",
                "Bomb Panic",
                "27 Gold Marbles",
                "Lily Pad Leapfrog 2",
                "The Mallet's Design",
                "At Cross Purposes",
                "Red and Blue Jewels",
                "Three Blocks",
                "Fixing the Pipes",
                "Bouncing Bombs",
                "Button to Button",
                "Murky Maze",
                "The Greatest Escape"
            },
            new string[]
            {
                "Bungle's Balloons",
                "Where's Mum?",
                "Bungle's Banners",
                "Dodgem Detective",
                "Robot Factory",
                "Bunny-hop Swap",
                "A Toasty Toast",
                "Carnival Colours",
                "Stamp Stumper",
                "The Long Wait",
                "Backstage Blunder",
                "Sharing the Burden",
                "Arte-facts",
                "Bite of Bygone Days",
                "Fix the Fossil",
                "Wandering Watches",
                "The Broken Brolly",
                "That's Juicy!",
                "Spinning Maize",
                "Nine Red Bricks",
                "A Lick of Paint",
                "Poke 'em Totems",
                "Fairway Fibber",
                "Patterned Apron",
                "Brave the Caves",
                "Mangled Maths",
                "That Rings a Bell",
                "Bunny-hop Swap 2",
                "Tenth-Round Ace",
                "Big Cake, Little Cake",
                "Emperor's Throne",
                "Target Practice",
                "Chained Circle",
                "The Cat's Trophy",
                "Twinkle Tops",
                "Going Dough-nuts!",
                "Spin Shenanigans",
                "Pattern Pending",
                "A Hat of Tiles",
                "Crossed Connections",
                "From the Sidelines",
                "Couple at the Cafe",
                "Pawn Portions",
                "Suit Crates",
                "From Left to Right",
                "Toppings Up!",
                "Trial by Tennis",
                "Lighting Action",
                "A Whinger's Tale",
                "Kitty Solitaire",
                "Dandy Bears",
                "Spectacular Views",
                "Poke 'em Totems 2",
                "Archaeological Feet",
                "Spinning Maize 2",
                "Clear-Cut Contrasts",
                "Stitching Squares",
                "Sorting Blocks",
                "Flowery Footpath",
                "A Ropey System",
                "Padlocked Gate",
                "Shattered Sign",
                "A Muddy Mess",
                "Norwell's Secret",
                "Kitty Solitaire 2",
                "A Trip to the Hospital",
                "Language of Love",
                "Days of Rest",
                "Toppings Up! Part 2",
                "A Perilous Adventure",
                "Pawn Portions 2",
                "A Cup of Tiles",
                "Rock Hard Sums",
                "Bunny-hop Swap 3",
                "Grand Horse Race",
                "Painstaking Packing",
                "Mishmash Map",
                "Three Clowns",
                "The Shopkeepers",
                "Sharing the Burden 2",
                "King Arthur's Sword",
                "Rainbow Repair",
                "Settle the Scores",
                "Neon Orange",
                "Slot Sequence",
                "Even Ten",
                "Merry-Go-Tiles",
                "Glass Arrows",
                "Pumpkin Spinners",
                "Loose Connection",
                "Totem Tumbler",
                "Ancient Artistry",
                "Hershel vs Mummies!",
                "Cursed Case",
                "Snakes and Keys",
                "Arach-attack!",
                "Tilt to Traverse",
                "Watertight Code",
                "Ancient Artistry 2",
                "The Last Door",
                "Wonky Wiring",
                "Dice Crates",
                "Stars of the Stage",
                "A Cracking Read",
                "Free Lunch!",
                "Confusion Cubed",
                "Toppings Up! Part 3",
                "Balls and Boxes",
                "Fishy Triangle",
                "Cosy Cabins",
                "Holiday Snaps",
                "A Duck of Tiles",
                "Chip Champions",
                "Emperor's Throne 2",
                "Slot Sequence 2",
                "Fair Lettering Ferris",
                "Ride Rotation",
                "Pawn Portions 3",
                "Fairly Shared Squares",
                "Bungle's Balloons 2",
                "Ball Dart Bullseye",
                "Kitty Solitaire 3",
                "Weighted Marbles",
                "Bungle's Banners 2",
                "A Day at the Races",
                "Room 2134 Mystery",
                "Ace of Diamonds",
                "Faded Photos",
                "A Sweeping Solution",
                "Water, Wood, Fire",
                "Jewels to the Lock",
                "Stealth Night",
                "Grand Hall Rescue",
                "Breaking the Seal",
                "Wind-Up Chamber",
                "A Pattern of Tiles",
                "Cursed Case 2",
                "Poke 'em Totems 3",
                "Eperor's Throne 3",
                "Pawn Portions 4",
                "Fix the Fossil 2",
                "Spinning Maize 3",
                "Flowery Footpath 2",
                "Grand Hall Rescue 2",
                "Merry-Go-Tiles 2",
                "Tilt to Traverse 2",
                "That Rings a Bell 2",
                "Mummies' Revenge!",
                "From Right to Left",
                "Back to the Chamber"
            },
            new string[]
            {
                "Airship's Destination",
                "A Glacial Gift",
                "Lighten Up",
                "Similar Snowflakes",
                "Embroidery Enigma",
                "Frozen in Time",
                "Mutiny!",
                "Reggie's Slidy Ride",
                "Dial Trial",
                "Funky Hooks",
                "A Laborious Litre",
                "Squirrel Snacks",
                "Pretty Paper Petals",
                "Blooming Flowers",
                "Something Fishy",
                "Give Me a Sign!",
                "Walking on Water",
                "The Celestial King",
                "A Dog of Tiles",
                "Boat to Boat",
                "Fishing Friends",
                "Hose Help?",
                "Choc-Full",
                "Mutual Meeting Place",
                "Cracking Combinations",
                "Copy Cats",
                "A Heart of Tiles",
                "Directing a Delivery",
                "Carriages of Justice",
                "Airship's Destination 2",
                "For the Heart!",
                "Bibliofiling",
                "Shopping Spree",
                "The Future Awaits",
                "Fake Fragments",
                "Fuel's Errand",
                "Fuel's Errand 2",
                "A Royal Burden",
                "Strawberry Sharer",
                "Acorn Allocation",
                "Shunting into Sidings",
                "A Boatload of Hassle",
                "A String of Jewels",
                "Staged Silhouettes",
                "Piglet Racing",
                "Blooming Flowers 2",
                "Fowl Food",
                "Acorn Allocation 2",
                "Fussy Fruit Eaters",
                "Forest Friends",
                "Baby Boar Racing",
                "An Epic Quest",
                "The Domino Effect",
                "A Trio of Trouble",
                "Very Specific Scoops",
                "Give Me a Sign! 2",
                "A Boatload of Trouble",
                "Nose to Nose",
                "Lovely Pairs",
                "Boat to Boat 2",
                "Be My Guest",
                "Nose to Nose 2",
                "Horsing Around",
                "Thick As Thieves",
                "Cards on the Table",
                "Flying the Coop",
                "A Feathered Apple",
                "Burger Building",
                "Bibliofiling 2",
                "A Knightly Trial",
                "Burger Building 2",
                "Bemused Bunnies",
                "Counting Sheep",
                "Pampering Your Pets",
                "Golden Butterfly",
                "Troubled Waters",
                "Fruits and Fungi",
                "All Under Control",
                "Snake Squeezing x10",
                "Golden Butterfly 2",
                "Moonlight, Starlight",
                "Walking on Water 2",
                "Snake Squeezing x11",
                "Potion Placement",
                "The Phoenix Wakes",
                "Reggie's Slidy Ride 2",
                "A Shamefaced Clock",
                "Bibliofiling 3",
                "Jewellery Jumble",
                "Very Specific Scoops 2",
                "A Ship of Tiles",
                "Tank Goodness",
                "Stacks of Stock",
                "Tethered Ted",
                "Troubled Waters 2",
                "Perplexing Patterns",
                "Pumpkin Purveyors",
                "A Troublesome Tent",
                "Brownie Points",
                "Directing a Delivery 2",
                "In the Balance",
                "Troubled Waters 3",
                "Poster Predator",
                "Finding Ambrosia",
                "Slicing Things Up",
                "Tethered Ted 2",
                "Lighten Up 2",
                "The Path of True Love",
                "A Slippery Surface",
                "Pesky Patterns",
                "Stacks of Stock 2",
                "A Puzzling Pyramid",
                "Shunting into Sidings 2",
                "Copy Cats 2",
                "Dial Trial 2",
                "Funky Hooks 2",
                "A Laborious 9 Litres",
                "Mutiny! 2",
                "Jumbled Junctions",
                "Snoozysnore's Plan!",
                "Touch Ten Buttons",
                "Snoozysnore Returns!",
                "Nose to Nose 3",
                "A Slippery Surface 2",
                "Stacks of Stock 3",
                "Thirst for Answers",
                "Bemused Bunnies 2",
                "Shunting into Sidings 3",
                "Tough-to-Reach Tea",
                "Mixed Swine Racing",
                "Forest Friends 2",
                "An Epic Quest 2",
                "A Boatload of Bother",
                "Airship's Destination 3",
                "A String of Jewels 2",
                "Directing a Delivery 3",
                "A Troublesome Tent 2",
                "In the Balance 2",
                "A Puzzling Pyramid 2",
                "Potion Placement 2",
                "Thick As Thieves 2",
                "X Marks...?",
                "The Azran Eggs",
                "Medal Match-Up",
                "Riddle-Me-Key",
                "Sprint and Switch!",
                "Room of Doom",
                "A Groovy Lever",
                "Exit on the Left",
                "The Azran Legacy",
                "Fuel's Errand 3",
                "Touch Ten Buttons 2",
                "Room of Doom 2",
                "Reggie's Slidy Ride 3",
                "Burger Building 3",
                "Lighten Up 3",
                "Funky Hooks 3",
                "A Puzzling Pyramid 3",
                "Blooming Flowers 3",
                "Sprint and Switch! 2",
                "A Groovy Lever! 2",
                "Exit on the Left 2",
                "Mutiny! 3",
                "Snoozysnore Strikes!",
                "A Troublesome Table"
            }
        };
    }
}